E1337Kat/cyberpunk2077_ext_redux

- src/index.ts
Basic INI mod support (need to add guards for Reshade and possibly Red4ext) to close #2 .
> Add INI mod support (#2)

- src/index.ts
Because we were only checking for .lua, for example .json files were not included explicitly - but because the folder was, they ended up being attempted to be copied, which Vortex caught and complained about (...but still installed the other files, sigh).
> Fix some CET mod files getting left out

- package-lock.json
- package.json
- src/index.ts
- src/installers.ts
- test/unit/installer-fix.test.ts
- test/unit/installer-select.test.ts
- test/unit/mods.example.ts
- test/unit/utils.helper.ts
The Vortex API provides things we want like notifications and the ability to create dialogs and UIs — just need to wrap our functions to pass in the API object only available in the register callback.
POC notification message.
> Add Notification Mechanism To Test/Install Functions (Plus Other Vortex API Access)

- package-lock.json
- package.json
- src/installers.ts
- test/unit/installer-fix.test.ts
- test/unit/installer-select.test.ts
- test/unit/mods.example.ts
- test/unit/utils.helper.ts
Maybe the test setup is finally getting kinda there. Probably easiest to look at the full files rather than the diff.
Closes #27 and #36
> Redscript Support (And Lots Of Test Refactors)

- test/unit/installer-select.test.ts
- test/unit/mods.example.ts
Just a tiny PR that fixes the JSON test failing, thanks to Auska :)
> Separate support failures from install failures

- package-lock.json
- package.json
- src/dialogs.ts
- src/installers.ts
- test/unit/installer-fix.test.ts
- test/unit/installer-select.test.ts
- test/unit/mods.example.ts
It fails one of the tests I set for it, but it works in Vortex with real files
> Reshade and INI handling

- src/dialogs.ts
- src/filetree.ts
- src/installers.ts
- test/unit/filetree.test.ts
- test/unit/installer-fix.test.ts
- test/unit/mods.example.ts
- test/unit/utils.helper.ts
Make the thing a little nicer.
> ArchiveOnly Retains Subdirs + FileTree Abstraction

- src/installers.ts
- test/unit/mods.example.ts
Looks like a merge mistake.  Surprised none of us caught it
> Re-enable the INI handlers

- src/installers.ts
Just a quick fix, I should probably make this a layout later, but I wanted something that would work for now
> Allow AMM mods with JSON to hit the fallback

- src/installers.layouts.ts
- src/installers.ts
- test/unit/mods.example.ts
Reverts E1337Kat/cyberpunk2077_ext_redux#87
> Revert "MultiType Supports Basedir Red4Exts"

- test/unit/mods.example.ts
Looks like the single pipeline work in #102 solved #116.  Simply added a test to make sure it works
> Add test for Redscript patches as reported in #116

- src/installers.layouts.ts
- src/installers.ts
- test/unit/mods.example.ts
Also added a test to help catch future regressions in this area.  I probably should have put `bin/x64/plugins/cyber_engine_tweaks/mods/AppearanceModMenu/` into a constant for readability....
> Fix regression of JsonAmm hotfix

- package-lock.json
- package.json
Gonna follow with a second, but I want to see if I can get some feedback from AMM users/devs.
> 0.6.0-gonk

- src/installer.config.xml.ts
- src/installers.layouts.ts
- test/unit/mods.example.config.xml.ts
- test/unit/mods.example.multitype.ts
- test/unit/mods.example.ts
- test/unit/utils.helper.ts
[Input Loader](https://www.nexusmods.com/cyberpunk2077/mods/4575) can merge (some) XML files. The candidates go in `.\r6\input\`.
> ✨ Support Mergeable XML Mods In r6/input/ For Input Loader

- src/index.ts
- src/installer.core.deprecated.ts
- src/installer.core.ts
- src/installers.ts
- src/ui.dialogs.ts
- test/unit/mods.example.deprecated.ts
- test/unit/mods.example.ts
Addresses #147.  Presents the user with dialogs explaining that the tool is deprecated
> Remove CSVMerge/WolvenKit

- src/installer.core.inputloader.ts
- src/installers.layouts.ts
- src/installers.ts
- src/installers.types.ts
- test/unit/mods.example.core.inputloader.ts
- test/unit/mods.example.ts
- test/unit/utils.helper.ts
Had to redo this because the other PR had a bunch of extraneous stuff in it.  Closes #168
> Initial explicit support for CoreInputLoader

- src/installer.preset.ts
- src/installers.layouts.ts
- src/installers.ts
- src/installers.types.ts
- test/unit/mods.example.preset.ts
- test/unit/mods.example.ts
- test/unit/utils.helper.ts
Support installing `*.preset` files
> ✨ Character Preset Support (For Appearance Change Unlocker?)

- src/installer.core.cybercat.ts
- src/ui.dialogs.ts
- src/ui.notifications.ts
- test/unit/installer-pipeline.test.ts
The mock implementation is bad, and needs to be fixed AND need to add a test for the non-auto-enable as well. But checked that manually, so this'll have to do.
> ✨ Info Notif vs. Dialog Based On User Automation Settings

- src/installer.preset.ts
- src/installers.layouts.ts
- src/installers.shared.ts
- test/unit/mods.example.preset.ts
Legacy style still supported too.
> 🐛 Fem/Masc Preset Support For Appearance Change Unlocker Presets

- package-lock.json
- package.json
- src/redmodding.ts
- src/ui.dialogs.ts
Added the ability to open GOG Galaxy when directing the user to the REDmod DLC. Added the ability to open the Epic Games app when directing the user to the REDmod DLC.
> GOG and Epic app support

- CHANGELOG.md
- package-lock.json
- package.json
Quiet release to add support for upcoming Red4ext.
> 🔖 v0.8.3 "Third's the Charm, TAKEMURA"

- .github/workflows/testing.yml
> 💚 [WIP] try to install dependencies in CI

- .github/workflows/packaging.yml
Consider merge commits on full releases
> 👷 Always package a fresh dev release on push to main

- package-lock.json
- package.json
Bump the version so we're not working on 0.9.2 tags anymore.
> 🔖💀 v0.9.3-gonk

- package-lock.json
- package.json
> 💀 v0.9.6-gonk

- src/installer.core-archive-xl.ts
- src/installers.layouts.ts
- test/unit/mods.example.core.archivexl.ts
Issue #335 
🐛 ⬆️ [#335] [Include ArchiveXL redscript file for core AXL install](https://github.com/E1337Kat/cyberpunk2077_ext_redux/commit/438d2d857614ab10fd94e887902272e1a85082c5)
🚨 Linting around
> 🐛 ⬆️ [#335] Include ArchiveXL redscript file for core AXL install

- package-lock.json
- package.json
> 🔖 [release] 0.9.6 - AXL update

- CHANGELOG.md
- package-lock.json
- package.json
- src/installer.redscript.ts
- src/installers.layouts.ts
- src/installers.shared.ts
- test/unit/mods.example.multitype.ts
- test/unit/mods.example.redscript.ts
- test/unit/utils.helper.ts
> 🐛 Support Redscript Config Files

- script/package.ps1
Apparently you have to escape the quote in ps, but not bash...
> 💚 Actually have pwsh packaging script work

- src/installer.core.inputloader.ts
- src/installers.layouts.ts
- test/unit/mods.example.core.inputloader.ts
> ✨⚛️ Support Core Input Loader v0.1.1 (and v0.1.0 with Deprecation)

- src/load_order.ts
- src/load_order.types.ts
- src/redmodding.metadata.ts
- test/unit/loadorder.example.ts
- test/unit/loadorder.test.ts
- fixes command length always and forever :smile_cat:
> ✨ Implementation base modlist file usage

- package-lock.json
- package.json
> 🔖 [release] bump version to 0.10.1

- CHANGELOG.md
- package-lock.json
- package.json
Bump the version, update the changelog
> 🔖 [release] bump version to 0.10.2

- src/installer.redmod.ts
- src/installers.layouts.ts
- test/unit/mods.example.redmod.ts
> ✨ [#382] Add support for ep1 tweaks

- CHANGELOG.md
- package-lock.json
- package.json
> 🔖 [release] bump version to 0.10.3

- .github/workflows/packaging.yml
- .github/workflows/testing.yml
accidentally pushed the actual changes directly to main. luckily the CI broke so I have to do this in a PR.... yayyy.
> 👷‍♀️ update CI config

- CHANGELOG.md
- package-lock.json
- package.json
> 🔖 [release] v0.11.4 AMM pose fixes
